language: ruby
rvm:
- 2.2.1
script: bundle exec rspec spec
branches:
  only:
  - master
env:
  global:
  - secure: OVLl33Padw2aziHCTCV274BOnxPFXhypzv0Z8T4JXvWxDxTIiD1VWP3Y2UFrlon7aU0Aj8yG0NIL2/VxuG0ajxjm7HrEDQtH4dtm8m9jwYYKwq3VD4O/Qg9USmzFUDUSFBSNeKB8zBN67gaCmWu+JiiwwzzZp490vdvom2NWpX5Aj4Wn7sq/2r5A+d5tVMInDS8MwzguIHJ8s7oAK8NoAFk1SDDfJR0Wwq28N/kosTFmhIxkHYunuEviS+av/JPShx636UOMoljOb40xsaN3sdWKRdZg5UknVwjxT3gKAGO38DdN4is+sBJf+06nz58FR7n/0aTXtjzJS3bwyMFBC8PeOkFiLyro9YOGwSBCMRt4K8S993Z9KfWwM4LDQKhQFEKaesPTaBwIcoihcFuAplZQEnm7Z82yLUp2revGf85k1zFLebsegZx0Yd/yMIW63W2wGi1OHGFH5ZT4CJtXOY8iax4AJIByLz56NyMH2PgjQ4kPbqW+Lmkdd2Tf63WOpW0ObaO9ah/u00tkd3YcJfLLsXh32170a4dOX1APv8hGRfpW0+b+LJFvZFZVY/VettGrS55EjUAkrmFvQY1fBEpqMPUBS4SEOSqh2Tpho5i0FLyOi4NxO7ePtNyypN4m3iQdwFf7PN7ekJlHWNBDmMjXxjzjUYEjq+us69dImzg=
